ChatCompletion(
    id='chatcmpl-b0c81238ae354ef5b099b0c1ea005796', 
    choices=[Choice(
        finish_reason='tool_calls', 
        index=0, 
        logprobs=None, 
        message=ChatCompletionMessage(
            content=None, 
            refusal=None, 
            role='assistant', 
            annotations=None, 
            audio=None, 
            function_call=None, 
            tool_calls=[ChatCompletionMessageToolCall(
                id='chatcmpl-tool-04985356c20f41d98235701003953912', 
                function=Function(arguments='{"target": "kitchen table"}', name='navigate_to_target'), 
                type='function'
            )], 
            reasoning_content=None
        ), 
        stop_reason=None
    )], 
created=1751276338, 
model='/share/project/liangdong/Qwen/Qwen2.5-7B-Instruct', 
object='chat.completion', 
service_tier=None, 
system_fingerprint=None, 
usage=CompletionUsage(
    completion_tokens=23, 
    prompt_tokens=476, 
    total_tokens=499, 
    completion_tokens_details=None, 
    prompt_tokens_details=None
), 
prompt_logprobs=None, 
kv_transfer_params=None)